import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.fundo,
  },
  headerBar: {
    height: 72,
    backgroundColor: colors.superficieSecundaria,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.borda,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.textoInverso,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 28,
  },
  avatarCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.superficie,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.borda,
  },
  headingHello: {
    marginTop: 16,
    fontSize: 28,
    fontWeight: '800',
    color: colors.textoPrimario,
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  headingWelcome: {
    marginTop: 4,
    fontSize: 18,
    fontWeight: '600',
    color: colors.textoPrimario,
    textAlign: 'center',
  },
  fieldLabel: {
    fontSize: 12,
    color: colors.textoPrimario,
    marginTop: 18,
    marginBottom: 6,
  },
  inputPill: {
    backgroundColor: colors.superficie,
    borderWidth: 1,
    borderColor: colors.borda,
    borderRadius: 24,
    paddingVertical: 10,
    paddingHorizontal: 14,
    color: colors.textoPrimario,
    fontSize: 14,
  },
  passwordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  forgotLink: {
    marginTop: 8,
    color: colors.textoTerciario,
    fontSize: 12,
  },
  divider: {
    height: 1,
    backgroundColor: colors.borda,
    marginVertical: 16,
  },
  signupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  signupText: {
    color: colors.textoPrimario,
    fontSize: 14,
  },
  signupButton: {
    backgroundColor: colors.superficie,
    borderWidth: 1,
    borderColor: colors.borda,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 16,
  },
  signupButtonText: {
    color: colors.textoPrimario,
    fontSize: 14,
    fontWeight: '600',
  },
  enterButton: {
    backgroundColor: colors.superficie,
    borderWidth: 1,
    borderColor: colors.borda,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 24,
    minWidth: 110,
    alignItems: 'center',
    justifyContent: 'center',
  },
  enterText: {
    color: colors.textoPrimario,
    fontSize: 14,
    fontWeight: '700',
  },
  footer: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    alignItems: 'center',
  },
  footerText: {
    textAlign: 'center',
    color: colors.textoTerciario,
    fontSize: 10,
    lineHeight: 14,
  },
});
