// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const EXTERNAL_AUTH_TABLES = [
  "auth.audit_log_entries",
  "auth.custom_oauth_providers",
  "auth.flow_state",
  "auth.identities",
  "auth.instances",
  "auth.mfa_amr_claims",
  "auth.mfa_challenges",
  "auth.mfa_factors",
  "auth.oauth_authorizations",
  "auth.oauth_client_states",
  "auth.oauth_clients",
  "auth.oauth_consents",
  "auth.one_time_tokens",
  "auth.refresh_tokens",
  "auth.saml_providers",
  "auth.saml_relay_states",
  "auth.schema_migrations",
  "auth.sessions",
  "auth.sso_domains",
  "auth.sso_providers",
  "auth.users",
  "auth.webauthn_challenges",
  "auth.webauthn_credentials",
];

const EXTERNAL_AUTH_ENUMS = [
  "auth.aal_level",
  "auth.code_challenge_method",
  "auth.factor_status",
  "auth.factor_type",
  "auth.oauth_authorization_status",
  "auth.oauth_client_type",
  "auth.oauth_registration_type",
  "auth.oauth_response_type",
  "auth.one_time_token_type",
];

export default defineConfig({
  schema: "prisma/schema.prisma",
  experimental: {
    externalTables: true,
  },
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7 moveu as URLs de conexão para este arquivo.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
  // Objetos do auth são gerenciados pelo Supabase e não pelo Prisma Migrate.
  tables: {
    external: EXTERNAL_AUTH_TABLES,
  },
  enums: {
    external: EXTERNAL_AUTH_ENUMS,
  },
});
